=== fiap-four-lanches/fourlanches.payment.app/src/test/resources/schema/Payment.schema.json
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "$id": "http://example.com/example.json",
    "type": "object",
    "required": [
        "id",
        "customerId",
        "order",
        "status",
        "isApproved",
        "createdAt",
        "updatedAt",
        "externalReference",
        "externalMetadata"
    ],
    "properties": {
        "id": {
            "type": "string"
        },
        "customerId": {
            "type": "integer"
        },
        "order": {
            "type": "object",
            "required": [
                "id",
                "totalPrice",
                "description"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "totalPrice": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                }
            }
        },
        "status": {
            "type": "string"
        },
        "isApproved": {
            "type": "boolean"
        },
        "createdAt": {
            "type": "string"
        },
        "updatedAt": {
            "type": "string"
        },
        "externalReference": {
            "type": "string"
        },
        "externalMetadata": {
            "type": "object",
            "required": [
                "externalReference"
            ],
            "properties": {
                "externalReference": {
                    "type": "string"
                }
            }
        }
    }
}

=== fiap-four-lanches/fourlanches.payment.app/src/test/resources/payments.json
{
    "id": "IdAlreadyCreated",
    "customerId": 1,
    "order": {
      "id": 2,
      "totalPrice": 99,
      "description": "Description of seeded payment"
    },
    "status": "created",
    "isApproved": true,
    "createdAt": "2024-01-27T13:50:20.337Z",
    "updatedAt": "2024-01-27T13:50:20.337Z",
    "externalReference": "string",
    "externalMetadata": {
      "externalReference": "string"
    }
  }
